### ISSUE TITLE
Where do I get simulation-gazebo?

### ISSUE THREAD

**Issue by brean** [Brazilian-Institute-of-Robotics/simulation-gazebo_thruster#5]
rock_gazebo ( https://github.com/Brazilian-Institute-of-Robotics/simulation-rock_gazebo )
requires gazebo_thruster, which requires simulation/gazebo.
According to your naming scheme I would expect that there is a repo on github at 
Brazilian-Institute-of-Robotics/simulation-gazebo, but this repo does not exist.
So where do I get it?

**Comment by Thomio-Watanabe** [comment]
Nice reflex.  _simulation/gazebo_ is actually the simulator (Gazebo). 
Rock reads a package set (check the file source.yml at https://github.com/Brazilian-Institute-of-Robotics/bir.flat_fish-package_set), then the framework downloads the source code, compiles it and set the environment variables within the framework.

**Comment by doudou** [comment]
Hi @brean 

The rock-gazebo integration has its own project now ... See https://github.com/rock-gazebo/package_set

See also https://rock-core.github.io/rock-and-syskit for some instructions/tutorial on how to set up an environment with Gazebo. It's Syskit specific, but even if you are not using Syskit there should be some useful information for you there.
